/* Copyright (C) 2010 Mikhail Osipov <mike.osipov@gmail.com> */
/* Published under the GNU General Public License V.2, see file COPYING */

#ifndef MBB_XML_MSG_H
#define MBB_XML_MSG_H

#include "xmltag.h"

typedef enum {
	MBB_MSG_OK,
	MBB_MSG_EMPTY,
	MBB_MSG_UNKNOWN_METHOD,
	MBB_MSG_XTV_MISSED,
	MBB_MSG_XTV_INVALID,
	MBB_MSG_TIME_MISSED,
	MBB_MSG_UNKNOWN_INET,
	MBB_MSG_UNKNOWN_UNIT,
	MBB_MSG_PSTART_MORE_END,
	MBB_MSG_PEND_LESS_START,
	MBB_MSG_INVALID_TIME_ORDER,
	MBB_MSG_UNIT_FREEZED,
	MBB_MSG_NAME_EXISTS,
	MBB_MSG_UNKNOWN_CONSUMER,
	MBB_MSG_HAS_CHILDS,
	MBB_MSG_UNPOSSIBLE,
	MBB_MSG_ORPHAN,
	MBB_MSG_TIME_ORDER,
	MBB_MSG_TIME_COLLISION,
	MBB_MSG_UNKNOWN_GROUP,
	MBB_MSG_UNKNOWN_USER,
	MBB_MSG_GROUP_HAS_USER,
	MBB_MSG_GROUP_HASNOT_USER,
	MBB_MSG_UNIT_HAS_CONSUMER,
	MBB_MSG_CONSUMER_FREEZED,
	MBB_MSG_SELF_NOT_EXISTS,
	MBB_MSG_INVALID_PASS,
	MBB_MSG_NEED_PASS,
	MBB_MSG_INET_COLLISION,
	MBB_MSG_INET_CROSS,
	MBB_MSG_AMBIGUOUS_REQUEST,
	MBB_MSG_UNKNOWN_VAR,
	MBB_MSG_NOT_CAPABLE,
	MBB_MSG_INVALID_VALUE,
	MBB_MSG_VAR_READONLY,
	MBB_MSG_ADDR_EXISTS,
	MBB_MSG_UNKNOWN_GATEWAY,
	MBB_MSG_UNKNOWN_OPERATOR,
	MBB_MSG_GW_HAS_LINK,
	MBB_MSG_UNKNOWN_GWLINK,
	MBB_MSG_UNAUTHORIZED,
	MBB_MSG_HEADER_MISSED,
	MBB_MSG_INVALID_HEADER,
	MBB_MSG_VAR_NOT_INIT,
	MBB_MSG_UNKNOWN_MODULE,
	MBB_MSG_UNKNOWN_TASK,
	MBB_MSG_TASK_CREATE_FAILED,
	MBB_MSG_TIME_NOPARENT,
	MBB_MSG_ROOT_ONLY
} mbb_msg_t;

XmlTag *mbb_xml_msg_ok(void);
XmlTag *mbb_xml_msg_error(gchar *fmt, ...);
XmlTag *mbb_xml_msg_from_error(GError *error);
XmlTag *mbb_xml_msg(mbb_msg_t msg_no, ...);

gboolean mbb_xml_msg_is_ok(XmlTag *tag, gchar **msg);

#endif
